### ISSUE TITLE
"Premium Only" videos not Working

### ISSUE THREAD

**Issue by karurosu15** [skid9000/Crunchyroll-Downloader#26] opened 2019-01-25 20:31 UTC
When I put the link of an episode for premium (I am premium) does not download anything. It says it has been downloaded but it is not true.

**Checklist**

- [x] I checked if my issue is already referenced.
- [x] I use a release version (from a tag or master branch).
- [x] Youtube-DL is up to date
- [x] I use the version of .NET Framework that is recommended or better

**Describe the bug**

**To Reproduce**
1. '...'
2. '....'
3. '....'

**Expected behavior**

**Screenshots**

**Infos (please complete the following information):**
 - OS (from a cmd : winver) :
 - Youtube-DL version (from a cmd : "C:\ProgramData\Crunchy-DL\youtube-dl.exe --version"
 - Crunchyroll-Downloader version (click on the about button from MainWindow) :
 - Region of the Crunchyroll account :
 - URL of what you tried to download :

**Additional context**

**Comment by skid9000** [comment] 2019-01-27 12:44
Can you please fill the issue template ?

**Comment by karurosu15** [comment] 2019-01-28 18:46
where is the template??

**Comment by karurosu15** [comment] 2019-01-28 18:54
this is what appears to me when I put a premium chapter, I am premium.

![sin titulo](https://user-images.githubusercontent.com/46386990/51859050-88b0b900-2336-11e9-9d8f-6a94261d8f7d.jpg)

Another error that I have is that only the subtitles are downloaded in esLA, I put it down in esES and it does not work.

**Comment by skid9000** [comment] 2019-01-28 18:56
Have you tried to update youtube-dl ?

**Comment by karurosu15** [comment] 2019-01-28 18:59
every day search and update youtube-dl from the same crunchy downlad application, the latest version is today

**Comment by skid9000** [comment] 2019-01-28 19:02
Ok, have you tried to re-download your content ? (btw can you give me a link so i can test it on my side ?)

**Comment by karurosu15** [comment] 2019-01-28 19:03
https://www.crunchyroll.com/es-es/mob-psycho-100/episode-4-inside-evil-spirit-780923

**Comment by skid9000** [comment] 2019-01-28 22:57
It works fine on my side U_u

I updated your first post, please edit it to fill the template.

**Comment by karurosu15** [comment] 2019-01-29 19:48
> When I put the link of an episode for premium (I am premium) does not download anything. It says it has been downloaded but it is not true.
> 
> **Checklist**
> 
> * [x]  I checked if my issue is already referenced.
> * [x]  I use a release version (from a tag or master branch).
> * [x]  Youtube-DL is up to date
> * [x]  I use the version of .NET Framework that is recommended or better
> 
> **Describe the bug**
> when I put a premium user link does not download anything, I get an error. I am a premium user
>

> **Screenshots**
> 
![sin titulo](https://user-images.githubusercontent.com/46386990/51935546-743bf180-2406-11e9-9293-57201b5d6340.jpg)

> 
> **Infos (please complete the following information):**
> 
> * OS (from a cmd : winver) : windows 10 1809
> * Youtube-DL version (from a cmd : "C:\ProgramData\Crunchy-DL\youtube-dl.exe --version" 2019.1.30
> * Crunchyroll-Downloader version (click on the about button from MainWindow) : 1.2.7C
> * Region of the Crunchyroll account : Spain (spain) but it does not work from any region
> * URL of what you tried to download : any link for premium users
> 
> **Additional context**
> last Thursday or Friday it does not work for me,

**Comment by skid9000** [comment] 2019-01-30 08:22
Ok i successfully reproduced the issue, but it seems more like a youtube-dl one...
I will see what i can do.

**Comment by skid9000** [comment] 2019-01-30 12:24
Ok i found the issue, it's on the CrunchyrollAuth side.

**Comment by karurosu15** [comment] 2019-01-30 12:55
otherwise, when I select subtitles I put es (es) but it automatically does it in es (lat)

**Comment by skid9000** [comment] 2019-01-30 14:29
for every video or just the "Premium Only" one ?

**Comment by karurosu15** [comment] 2019-01-30 14:34
every video

**Comment by skid9000** [comment] 2019-01-30 14:35
Ok, i will check that in the evening if i have some time...

**Comment by karurosu15** [comment] 2019-01-30 14:36
And the issue of download?

**Comment by skid9000** [comment] 2019-01-30 14:37
It's because the cookie file is missing 2 new cookies, i need to check how to solve that...

**Comment by karurosu15** [comment] 2019-01-30 14:38
ok. Thank

**Comment by karurosu15** [comment] 2019-01-31 19:27
hello, I've used youtube-dl in a YouTube video and everything is fine. but I've put a crunchy video and the error comes out:

ERROR: This is a sample clip. To watch the full video, start the free trial !; please report this issue on https://yt-dl.org/bug. Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Is it something crunchy?

**Comment by karurosu15** [comment] 2019-02-04 19:35
Something new?

**Comment by guevara15** [comment] 2019-02-16 12:38
Hello, I'm also a premium user and the same thing happens to me, I can not download the premium chapters, but the rest. Also, the subtitles download it in es-Lat and not es-es
I have uninstalled everything, I have cleaned cache and temporary, I have reinstalled it, update youtube-dl and it still does not work
Do you need a tester user?

**Comment by skid9000** [comment] 2019-02-18 20:09
For the premium problem, it's in the CrunchyrollAuth module, so i opened a issue here : https://github.com/skid9000/CrunchyrollAuth/issues/2

For the subs, please open a separate issue with all the details, since i don't understand Es at all i can't do much ATM.

**Comment by karurosu15** [comment] 2019-03-20 11:10
with the new version 1.2.8 I can not download anything.

**Comment by skid9000** [comment] 2019-03-20 12:48
It will be fixed when i will find and release a fix for CrunchyrollAuth...

**Comment by ClemPera** [comment] 2019-03-23 15:42
Same here, do you have a temporary solution to propose us to manually bypass that ?

**Comment by skid9000** [comment] 2019-03-23 15:44
Update to 1.2.9.

For non-premium only vids, leave it as it is
If you want premium only vids, you need to login to Crunchyroll from your webbrowser and export a cookie file to C:\ProgramData\Crunchy-DL\cookies.txt

**Comment by ClemPera** [comment] 2019-03-23 16:17
Thanks it works :)

**Comment by Xorima** [comment] 2019-03-24 20:09
Just a heads up I have some other code that does similar in python and using phantomjs webdriver and selenium enables me to grab out the cookies after login etc:

**Comment by skid9000** [comment] 2019-03-29 16:29
Welp seems like the login feature from yt-dl is working again, will be implementing a new way to handle that in crdl for the 2.0 ^^

**Comment by skid9000** [comment] 2019-03-30 13:05
Fixed in develop, will be in release 2.0.0.

**Closed as completed** 2019-03-30 13:05 UTC
Labels: bug, login module
