### ISSUE TITLE
Crunchyroll-DL wont even download anything

### ISSUE THREAD

**Issue by ghost** [skid9000/Crunchyroll-Downloader#29] opened 2019-02-28 03:31 UTC
**Checklist**

- [✓] I checked if my issue is already referenced.
- [✓] I use a release version (from a tag or master branch).
- [✓] Youtube-DL is up to date
- [✓] I use the version of .NET Framework that is recommended or better

**Describe the bug**
Youtube-DL is unable to download any Crunchyroll video. This isn't necessarily a crunchyroll downloader issue, but I feel like I should address is because it may be something wrong with the arguments.

**To Reproduce**
1. 'Run the download button from the GUI or input the arguments into youtube-dl.exe using cmd' (removing the quotation marks from the output directory argument)
2. See error

(the default arguments provided in Crunchyroll-Downloader had the error: at least one URL must be specified. so I removed the quotation marks from the output directory and now I'm getting a 503 server error)

**Expected behavior**
I expected it to download the video. That's all really :P

**Screenshots**

![capture](https://user-images.githubusercontent.com/31995736/53539404-76659e80-3adf-11e9-8683-ccf86566197f.PNG)

**Infos (please complete the following information):**
 - OS (from a cmd : winver) : Windows 7 Ultimate
 - Youtube-DL version (from a cmd : "C:\ProgramData\Crunchy-DL\youtube-dl.exe --version": 2019.02.18
 - Crunchyroll-Downloader version (click on the about button from MainWindow) : 1.2.7c
 - Region of the Crunchyroll account : USA
 - URL of what you tried to download : https://www.crunchyroll.com/a-centaurs-life/episode-1-when-all-is-said-and-done-everyone-loves-kisses-did-you-know-that-a-marathon-is-a-microcosm-of-life-742023

**Additional context**

I'll try tampering with the arguments if I can, but for now it doesn't download anything.

**Comment by ghost** [comment] 2019-02-28 03:31
(posted the wrong image, sorry xP)

**Comment by skid9000** [comment] 2019-02-28 06:56
It's youtube-dl related, i can't do much ATM if not just waiting the realase with a fix...
https://github.com/rg3/youtube-dl/issues/20027

**Comment by skid9000** [comment] 2019-02-28 16:29
I FOUND A FIX!

Will implement that ASAP.

**Comment by alikindsys** [comment] 2019-02-28 20:35
Wait did you? i thought it were CR's or YT-DL fault, getting the same error in ytdl.

**Comment by skid9000** [comment] 2019-02-28 20:40
I have pushed the fix in the develop branch.
Also you can check the issue i opened on youtube-dl repository.

**Comment by alikindsys** [comment] 2019-02-28 20:44
Nice that you keeped things organized. Will compile it soon afterwards and tell here the aftermath.

**Comment by alikindsys** [comment] 2019-02-28 21:05
I've compiled it and it executed the same way that stable did. 
By locating the commit that claimed to fix the issue and seeing what changed i've confirmed that i'm infact at the latest develop branch.
My Program.cs : 38 
```csharp
process.StartInfo.Arguments = $"--write-sub --sub-lang {Langue} --sub-format {Format} -f best --no-part -o \"{SavePath}\" --recode-video mkv --embed-subs --postprocessor-args \"-disposition:s:0 default\" --cookies C:\\ProgramData\\Crunchy-DL\\cookies.txt --download-archive C:\\ProgramData\\Crunchy-DL\\youtube-dl_archive.txt --user-agent 'Mozilla / 5.0 (Windows NT 10.0; Win64; x64; rv: 65.0) Gecko / 20100101 Firefox / 65.0' {Url}";
```
That's exactly the one @ https://github.com/skid9000/Crunchyroll-Downloader/blob/be8cdc778cff6d9381f8fa88be4bc614ed2e0bc7/Crunchyroll-Downloader/Program.cs#L38 seems that your fix worked locally and isn't global, pointing our worst scenario, it's up to yt-dl to fix or is a little better being an cloudflare 503 and will fix itself.

**Comment by skid9000** [comment] 2019-02-28 21:07
You need to use the same user agent that generated the cookie file.

**Comment by alikindsys** [comment] 2019-02-28 21:08
thats just an proof that i'm at latest.

**Comment by ghost** [comment] 2019-02-28 21:27
How exactly does one change the user agent? I used the CrunchyLogin exe to create a cookies file for me

**Comment by alikindsys** [comment] 2019-02-28 21:28
By the looks of it, the UA is hardcoded, so the only way is to find your browser UA and change it in the code. @Lugiia

**Comment by skid9000** [comment] 2019-02-28 21:29
It's hardcoded because the CrunchyrollAuth module will use the same UA.

**Comment by alikindsys** [comment] 2019-02-28 21:30
@skid9000  That makes sense, thus the fix should work. but it didnt (for me) the way i look at is that we have to wait till youtube-dl launches a fix or see if the 503 gets fixed by cloudflare.

**Comment by alikindsys** [comment] 2019-02-28 21:34
@Lugiia If you used the program itself to generate the cookies the UA shouldn't matter since its the same, don't bother with that.

**Comment by ghost** [comment] 2019-02-28 21:38
ah, okay

**Closed as completed** 2019-03-14 20:53 UTC
Labels: youtube-dl
