### ISSUE TITLE
Crash after dependencies download on Win7/8

### ISSUE THREAD

**Issue by UltrazaubererGer** [skid9000/Crunchyroll-Downloader#47] opened 2020-03-19 12:52 UTC
**Checklist**

- [x] I checked if my issue is already referenced.
- [x] I use a release version (from a tag or master branch).
- [x] Youtube-DL is up to date
- [x] I use the version of .NET Framework that is recommended or better

**Describe the bug**

**To Reproduce**
1. 'Install'
2. 'Run'
3. 'Crash'

**Expected behavior**
Programm starting

**Screenshots**
![CR Download Error](https://user-images.githubusercontent.com/62385579/77069109-20b0ac80-69e8-11ea-93a9-89c990340b08.jpg)

**Infos (please complete the following information):**
 - OS (from a cmd : winver) : Win7 Pro Version 6.1 Build 7601: Service Pack 1
 - Youtube-DL version (from a cmd : "C:\ProgramData\Crunchy-DL\youtube-dl.exe --version": 2020.03.08
 - Crunchyroll-Downloader version (click on the about button from MainWindow) : Not possible, Downloaded 2.1 today

**Additional context**
Problemsignatur:
  Problemereignisname:	CLR20r3
  Problemsignatur 01:	Crunchyroll-Downloader.exe
  Problemsignatur 02:	2.1.0.0
  Problemsignatur 03:	5e6ff4bb
  Problemsignatur 04:	mscorlib
  Problemsignatur 05:	4.8.4069.0
  Problemsignatur 06:	5dc614b0
  Problemsignatur 07:	2d74
  Problemsignatur 08:	2f
  Problemsignatur 09:	KUTS43RW3WMPE3EWT1R1Z5M5MTM1NR04
  Betriebsystemversion:	6.1.7601.2.1.0.256.48
  Gebietsschema-ID:	1031
  Zusatzinformation 1:	0a9e
  Zusatzinformation 2:	0a9e372d3b4ad19135b953a78882e789
  Zusatzinformation 3:	0a9e
  Zusatzinformation 4:	0a9e372d3b4ad19135b953a78882e789

**Comment by skid9000** [comment] 2020-03-19 13:24
I'm setting up a Windows 7 virtual machine right now to see if i can reproduce the issue.
Did you try on another version of windows ?

**Comment by UltrazaubererGer** [comment] 2020-03-19 15:04
Thank you!
I only have this version of windows installed.

**Comment by skid9000** [comment] 2020-03-19 16:02
Ok so i don't know why, but everything that is not Windows 10 dosen't work after downloading dependencies, that's weird.

If it only was Win7 that would have been a wontfix since Win7 isn't supported by Microsoft anymore but that affect Win8 and 8.1 too.

I'm going to do some investigation but atm i have no idea what's doing this.

**Comment by skid9000** [comment] 2020-03-19 18:02
Fixed with https://github.com/skid9000/Crunchyroll-Downloader/commit/f36493193d38e00fd14db95f9528a679d9982c36 

v2.1.1 should be out in the next few minutes.

**Comment by DynamicField** [comment] 2020-03-19 18:03
Actually this was due to Windows 10 allowing unknown cultures, not throwing any exceptions, but older versions of Windows threw an exception instead and made the app crash.

**Closed as completed by skid9000** 2020-03-19 18:02 UTC
Labels: bug

**Comment by UltrazaubererGer** [comment] 2020-03-19 23:44
v2.1.1 works perfectly, thank you very much for the quick fix!
