### ISSUE TITLE
Unable to download content.

### ISSUE THREAD

**Issue by Nano-Circuit** [skid9000/Crunchyroll-Downloader#45] opened 2020-03-16 21:08 UTC
**Checklist**

- [x] I checked if my issue is already referenced.
- [x] I use a release version (from a tag or master branch).
- [x] Youtube-DL is up to date
- [x] I use the version of .NET Framework that is recommended or better

**Describe the bug**
the downloader fails to download any video from crunchyroll. it throws up the same error about checking login, and url. i have already tripple checked url, tripple checked login, reset password, used a seperate account, done everything in and out of admin mode, reinstalled the downloader and all dependencies, and even done all of this on a seperate machine.

**To Reproduce**
1. 'fill out the download form'
2. 'click download'

**Expected behavior**
download begins

**Infos (please complete the following information):**
 - OS (from a cmd : winver) : win 10 home
 - Youtube-DL version (from a cmd : 2020.3.8.0
 - Crunchyroll-Downloader version  : 2.0.0
 - Region of the Crunchyroll account : USA
 - URL of what you tried to download : https://www.crunchyroll.com/that-time-i-got-reincarnated-as-a-slime/episode-13-the-great-clash-778587

**Additional context**
a few days ago, i tried to download a whole series via multiple windows. obviously, crunchyroll rate limited me. i waited a few days to try again, but one at a time this time, and was unable to download anything. i have used this tool many times before, and this is the only issue i have had with it.

**Comment by skid9000** [comment] 2020-03-16 21:19
My testing script works fine, so they haven't changed the login method which is good.
I'm recovering my debug environment to see if i can reproduce the issue.

**Comment by skid9000** [comment] 2020-03-16 21:25
Hm i can't reproduce, maybe your Crunchyroll account is flagged or something i don't know honestly.

**Comment by Nano-Circuit** [comment] 2020-03-16 21:36
@skid9000 i tried a different account though. is it possible for them to flag my  ip?

if so, i will be traveling in a few days. i can update if it works then.

**Comment by Nano-Circuit** [comment] 2020-03-18 21:16
@skid9000 it seems to be working now. no idea what changed.

**Comment by skid9000** [comment] 2020-03-18 22:06
Maybe a temp ban 🤔, honestly i don't know anymore who to blame if not CloudFlare, Crunchyroll and / or myself.

Anyway i'm closing this :)

**Closed as completed by skid9000** 2020-03-18 22:06 UTC
Labels: bug, Not confirmed
